
[en]
  title = "IT-Teaching"
  LanguageName = "English"
  weight = 1

[de]
  title = "IT-Teaching"
  LanguageName = "German"
  weight = 1

[pt]
  title = "Claridade" # just for the sake of showing this is possible
  LanguageName = "PortuguÃªs"
  weight = 2
  